services:
  redpanda:
    image: redpandadata/redpanda:latest
    container_name: livetrack-redpanda
    ports:
      - "9092:9092"
      - "19092:19092"
      - "9644:9644"
    command:
      - redpanda
      - start
      - --smp=1
      - --memory=512M
      - --reserve-memory=0M
      - --overprovisioned
      - --node-id=0
      - --kafka-addr=internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr=internal://redpanda:9092,external://localhost:19092

  postgres:
    image: postgres:16
    container_name: livetrack-postgres
    environment:
      POSTGRES_DB: livetrack
      POSTGRES_USER: livetrack
      POSTGRES_PASSWORD: livetrack
    ports:
      - "5432:5432"

  console:
    image: redpandadata/console:latest
    container_name: livetrack-console
    ports:
      - "8090:8080"
    environment:
      KAFKA_BROKERS: redpanda:9092
    depends_on:
      - redpanda
